### ISSUE TITLE
[Feature Request] `ecs_task.wait>` operator supports changeable interval and storategy(like exponential backoff)

### ISSUE THREAD

**Issue by Mulyu** [civitaspo/digdag-operator-ecs_task#42]
=== added by @civitaspo for writing an English translation ===

Thank you for your work. As I tried to use this plugin, some cases are that too much logs are outputted because `ecs_task.wait` operator polls each second and outputs a log each time. So, I think that it's better that `ecs_task.wait` operator supports changeable polling interval and polling storategy. What do you think about this? As for the latter, it seems that aws sdk does not support exponential backoff storategy so its own implementation is required.

=== the original text is below ===

素晴らしいプラグインをありがとうございます:bow:

実際に利用を検討していたところ、タスクの待機の間隔が固定値1秒になっており、ログも都度出力されるのでdigdagで確認したときにログが流れすぎるなーと思う場面がありました。
待機の間隔を可変、もしくはexponential backoffでできればいいなと思うのですが、いかがでしょうか？
後者はawsのsdkのDelayStrategyが(確認した範囲では)存在しないようなので、自前の実装になりそうですが...

(英語苦手なので日本語で失礼します:bow:)

**Comment by civitaspo** [comment]
(This is an English translation of the description.)

Thank you for your work. As I tried to use this plugin, some cases are that too much logs are outputted because `ecs_task.wait` operator polls each second and outputs a log each time. So, I think that it's better that `ecs_task.wait` operator supports changeable polling interval and polling storategy. What do you think about this? As for the latter, it seems that aws sdk does not support exponential backoff storategy so its own implementation is required.
